name: Build and Test

on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.100
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: |
          dotnet test --configuration Release --no-restore --no-build \
                      --logger "trx;LogFileName=${{ github.workspace }}/logs/test-results.trx"
      - run: echo "PWD=$(pwd)" >> $GITHUB_ENV
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: XUnit Tests
          path: ${{ github.workspace }}/logs/test-results.trx
          reporter: dotnet-trx
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: ${{ github.workspace }}/logs/test-results.trx
